export const ERROR_CODE_ATTEMPT_FAILED = 'ERROR_ATTEMPT_FAILED';
export const ERROR_CODE_GENERIC = 'ERROR_GENERIC';
export const ERROR_CODE_NO_RESULTS = 'ERROR_NO_RESULTS';
export const ERROR_CODE_NO_URLS = 'ERROR_NO_URLS';
export const ERROR_CODE_UNAUTHORIZED = 'ERROR_UNAUTHORIZED';

// from API
export const ERROR_QUEUE_MAX_USED_DAY = 'ERROR_QUEUE_MAX_USED_DAY';
