name: Lighthouse Check
on: [pull_request]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - run: npm install
    - run: npm run build
    - name: Run Lighthouse Check
      env:
        PR_NUMBER: "$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"
      run: |
        echo "pr number $(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"
        node ./dist/bin/lighthouse-check.js --verbose \
        --urls "https://www.foo.software" \
        --prCommentEnabled true \
        --prCommentAccessToken ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }} \
        --prCommentUrl "https://api.github.com/repos/foo-software/lighthouse-check/pulls/$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')/reviews"
