name: Lighthouse Check
on: [pull_request]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Lighthouse Check
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - run: |
      npm run build
      node ./dist/bin/lighthouse-check.js --urls "https://www.foo.software"
