name: Lighthouse Check Failure
on: [pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - run: npm install
    - run: npm run build
    - name: Run Lighthouse Check
      run: |
        node ./dist/bin/lighthouse-check.js --verbose \
        --urls "https://www.foo.software/api/mockResponse/500"
