name: Test Issue 109
on: [pull_request]

jobs:
  build_and_test_lighthouse:
    name: Build and Test (Lighthouse).
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false && github.event.action != 'closed'
    steps:
    -
      uses: actions/checkout@v3
    -
      name: Build docker image
      run: docker build -t example:${{github.sha}} ${{ github.workspace }}/test-109
    -
      name: Start docker container
      run: docker run -d -p 8080:80 example:${{github.sha}}
    -
      name: Wait for fastboot to load
      run: sleep 20 && curl http://localhost:8080/
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - run: npm install
    - run: npm run build
    -
      name: Lighthouse Desktop
      id: lighthouse-desktop
      run: |
        node ./test-109/lighthouse-check-test.js
